/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables;


import com.databasir.dao.Databasir;
import com.databasir.dao.Keys;
import com.databasir.dao.tables.records.ProjectRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectTable extends TableImpl<ProjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>databasir.project</code>
     */
    public static final ProjectTable PROJECT = new ProjectTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectRecord> getRecordType() {
        return ProjectRecord.class;
    }

    /**
     * The column <code>databasir.project.id</code>.
     */
    public final TableField<ProjectRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>databasir.project.name</code>.
     */
    public final TableField<ProjectRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>databasir.project.description</code>.
     */
    public final TableField<ProjectRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>databasir.project.group_id</code>.
     */
    public final TableField<ProjectRecord, Integer> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>databasir.project.deleted</code>.
     */
    public final TableField<ProjectRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>databasir.project.deleted_token</code>. default is 0, it
     * will be set to {id} when deleted
     */
    public final TableField<ProjectRecord, Integer> DELETED_TOKEN = createField(DSL.name("deleted_token"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "default is 0, it will be set to {id} when deleted");

    /**
     * The column <code>databasir.project.create_at</code>.
     */
    public final TableField<ProjectRecord, LocalDateTime> CREATE_AT = createField(DSL.name("create_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private ProjectTable(Name alias, Table<ProjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProjectTable(Name alias, Table<ProjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>databasir.project</code> table reference
     */
    public ProjectTable(String alias) {
        this(DSL.name(alias), PROJECT);
    }

    /**
     * Create an aliased <code>databasir.project</code> table reference
     */
    public ProjectTable(Name alias) {
        this(alias, PROJECT);
    }

    /**
     * Create a <code>databasir.project</code> table reference
     */
    public ProjectTable() {
        this(DSL.name("project"), null);
    }

    public <O extends Record> ProjectTable(Table<O> child, ForeignKey<O, ProjectRecord> key) {
        super(child, key, PROJECT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Databasir.DATABASIR;
    }

    @Override
    public Identity<ProjectRecord, Integer> getIdentity() {
        return (Identity<ProjectRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProjectRecord> getPrimaryKey() {
        return Keys.KEY_PROJECT_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProjectRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PROJECT_UK_GROUP_ID_NAME_DELETED_TOKEN);
    }

    @Override
    public ProjectTable as(String alias) {
        return new ProjectTable(DSL.name(alias), this);
    }

    @Override
    public ProjectTable as(Name alias) {
        return new ProjectTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectTable rename(String name) {
        return new ProjectTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProjectTable rename(Name name) {
        return new ProjectTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Integer, Boolean, Integer, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
