/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * custom document description
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentDescriptionPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        content;
    private Integer       projectId;
    private String        tableName;
    private String        columnName;
    private Integer       updateBy;
    private LocalDateTime updateAt;
    private LocalDateTime createAt;

    public DocumentDescriptionPojo() {}

    public DocumentDescriptionPojo(DocumentDescriptionPojo value) {
        this.id = value.id;
        this.content = value.content;
        this.projectId = value.projectId;
        this.tableName = value.tableName;
        this.columnName = value.columnName;
        this.updateBy = value.updateBy;
        this.updateAt = value.updateAt;
        this.createAt = value.createAt;
    }

    public DocumentDescriptionPojo(
        Integer       id,
        String        content,
        Integer       projectId,
        String        tableName,
        String        columnName,
        Integer       updateBy,
        LocalDateTime updateAt,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.content = content;
        this.projectId = projectId;
        this.tableName = tableName;
        this.columnName = columnName;
        this.updateBy = updateBy;
        this.updateAt = updateAt;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.document_description.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.document_description.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.document_description.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>databasir.document_description.content</code>.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>databasir.document_description.project_id</code>.
     */
    public Integer getProjectId() {
        return this.projectId;
    }

    /**
     * Setter for <code>databasir.document_description.project_id</code>.
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * Getter for <code>databasir.document_description.table_name</code>.
     */
    public String getTableName() {
        return this.tableName;
    }

    /**
     * Setter for <code>databasir.document_description.table_name</code>.
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * Getter for <code>databasir.document_description.column_name</code>.
     */
    public String getColumnName() {
        return this.columnName;
    }

    /**
     * Setter for <code>databasir.document_description.column_name</code>.
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * Getter for <code>databasir.document_description.update_by</code>.
     */
    public Integer getUpdateBy() {
        return this.updateBy;
    }

    /**
     * Setter for <code>databasir.document_description.update_by</code>.
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * Getter for <code>databasir.document_description.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>databasir.document_description.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>databasir.document_description.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.document_description.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DocumentDescriptionPojo (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(projectId);
        sb.append(", ").append(tableName);
        sb.append(", ").append(columnName);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
