/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentFullText implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       groupId;
    private Integer       projectId;
    private Integer       databaseDocumentId;
    private Integer       databaseDocumentVersion;
    private Integer       tableDocumentId;
    private Integer       tableColumnDocumentId;
    private String        groupName;
    private String        groupDescription;
    private String        projectName;
    private String        projectDescription;
    private String        databaseName;
    private String        schemaName;
    private String        databaseProductName;
    private String        databaseType;
    private String        tableName;
    private String        tableComment;
    private String        tableDescription;
    private String        colName;
    private String        colComment;
    private String        colDescription;
    private LocalDateTime updateAt;
    private LocalDateTime createAt;

    public DocumentFullText() {}

    public DocumentFullText(DocumentFullText value) {
        this.id = value.id;
        this.groupId = value.groupId;
        this.projectId = value.projectId;
        this.databaseDocumentId = value.databaseDocumentId;
        this.databaseDocumentVersion = value.databaseDocumentVersion;
        this.tableDocumentId = value.tableDocumentId;
        this.tableColumnDocumentId = value.tableColumnDocumentId;
        this.groupName = value.groupName;
        this.groupDescription = value.groupDescription;
        this.projectName = value.projectName;
        this.projectDescription = value.projectDescription;
        this.databaseName = value.databaseName;
        this.schemaName = value.schemaName;
        this.databaseProductName = value.databaseProductName;
        this.databaseType = value.databaseType;
        this.tableName = value.tableName;
        this.tableComment = value.tableComment;
        this.tableDescription = value.tableDescription;
        this.colName = value.colName;
        this.colComment = value.colComment;
        this.colDescription = value.colDescription;
        this.updateAt = value.updateAt;
        this.createAt = value.createAt;
    }

    public DocumentFullText(
        Integer       id,
        Integer       groupId,
        Integer       projectId,
        Integer       databaseDocumentId,
        Integer       databaseDocumentVersion,
        Integer       tableDocumentId,
        Integer       tableColumnDocumentId,
        String        groupName,
        String        groupDescription,
        String        projectName,
        String        projectDescription,
        String        databaseName,
        String        schemaName,
        String        databaseProductName,
        String        databaseType,
        String        tableName,
        String        tableComment,
        String        tableDescription,
        String        colName,
        String        colComment,
        String        colDescription,
        LocalDateTime updateAt,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.groupId = groupId;
        this.projectId = projectId;
        this.databaseDocumentId = databaseDocumentId;
        this.databaseDocumentVersion = databaseDocumentVersion;
        this.tableDocumentId = tableDocumentId;
        this.tableColumnDocumentId = tableColumnDocumentId;
        this.groupName = groupName;
        this.groupDescription = groupDescription;
        this.projectName = projectName;
        this.projectDescription = projectDescription;
        this.databaseName = databaseName;
        this.schemaName = schemaName;
        this.databaseProductName = databaseProductName;
        this.databaseType = databaseType;
        this.tableName = tableName;
        this.tableComment = tableComment;
        this.tableDescription = tableDescription;
        this.colName = colName;
        this.colComment = colComment;
        this.colDescription = colDescription;
        this.updateAt = updateAt;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.document_full_text.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.document_full_text.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.document_full_text.group_id</code>. ref to
     * group.id
     */
    public Integer getGroupId() {
        return this.groupId;
    }

    /**
     * Setter for <code>databasir.document_full_text.group_id</code>. ref to
     * group.id
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * Getter for <code>databasir.document_full_text.project_id</code>. ref to
     * project.id, may null
     */
    public Integer getProjectId() {
        return this.projectId;
    }

    /**
     * Setter for <code>databasir.document_full_text.project_id</code>. ref to
     * project.id, may null
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * Getter for
     * <code>databasir.document_full_text.database_document_id</code>. ref to
     * database_document.id, may null
     */
    public Integer getDatabaseDocumentId() {
        return this.databaseDocumentId;
    }

    /**
     * Setter for
     * <code>databasir.document_full_text.database_document_id</code>. ref to
     * database_document.id, may null
     */
    public void setDatabaseDocumentId(Integer databaseDocumentId) {
        this.databaseDocumentId = databaseDocumentId;
    }

    /**
     * Getter for
     * <code>databasir.document_full_text.database_document_version</code>. rf
     * to database_document.version, may null
     */
    public Integer getDatabaseDocumentVersion() {
        return this.databaseDocumentVersion;
    }

    /**
     * Setter for
     * <code>databasir.document_full_text.database_document_version</code>. rf
     * to database_document.version, may null
     */
    public void setDatabaseDocumentVersion(Integer databaseDocumentVersion) {
        this.databaseDocumentVersion = databaseDocumentVersion;
    }

    /**
     * Getter for <code>databasir.document_full_text.table_document_id</code>.
     * ref to table_document.id, may null
     */
    public Integer getTableDocumentId() {
        return this.tableDocumentId;
    }

    /**
     * Setter for <code>databasir.document_full_text.table_document_id</code>.
     * ref to table_document.id, may null
     */
    public void setTableDocumentId(Integer tableDocumentId) {
        this.tableDocumentId = tableDocumentId;
    }

    /**
     * Getter for
     * <code>databasir.document_full_text.table_column_document_id</code>. ref
     * to table_column_document.id, may null
     */
    public Integer getTableColumnDocumentId() {
        return this.tableColumnDocumentId;
    }

    /**
     * Setter for
     * <code>databasir.document_full_text.table_column_document_id</code>. ref
     * to table_column_document.id, may null
     */
    public void setTableColumnDocumentId(Integer tableColumnDocumentId) {
        this.tableColumnDocumentId = tableColumnDocumentId;
    }

    /**
     * Getter for <code>databasir.document_full_text.group_name</code>.
     */
    public String getGroupName() {
        return this.groupName;
    }

    /**
     * Setter for <code>databasir.document_full_text.group_name</code>.
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * Getter for <code>databasir.document_full_text.group_description</code>.
     */
    public String getGroupDescription() {
        return this.groupDescription;
    }

    /**
     * Setter for <code>databasir.document_full_text.group_description</code>.
     */
    public void setGroupDescription(String groupDescription) {
        this.groupDescription = groupDescription;
    }

    /**
     * Getter for <code>databasir.document_full_text.project_name</code>.
     */
    public String getProjectName() {
        return this.projectName;
    }

    /**
     * Setter for <code>databasir.document_full_text.project_name</code>.
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * Getter for <code>databasir.document_full_text.project_description</code>.
     */
    public String getProjectDescription() {
        return this.projectDescription;
    }

    /**
     * Setter for <code>databasir.document_full_text.project_description</code>.
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription;
    }

    /**
     * Getter for <code>databasir.document_full_text.database_name</code>.
     */
    public String getDatabaseName() {
        return this.databaseName;
    }

    /**
     * Setter for <code>databasir.document_full_text.database_name</code>.
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName;
    }

    /**
     * Getter for <code>databasir.document_full_text.schema_name</code>.
     */
    public String getSchemaName() {
        return this.schemaName;
    }

    /**
     * Setter for <code>databasir.document_full_text.schema_name</code>.
     */
    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }

    /**
     * Getter for
     * <code>databasir.document_full_text.database_product_name</code>.
     */
    public String getDatabaseProductName() {
        return this.databaseProductName;
    }

    /**
     * Setter for
     * <code>databasir.document_full_text.database_product_name</code>.
     */
    public void setDatabaseProductName(String databaseProductName) {
        this.databaseProductName = databaseProductName;
    }

    /**
     * Getter for <code>databasir.document_full_text.database_type</code>.
     */
    public String getDatabaseType() {
        return this.databaseType;
    }

    /**
     * Setter for <code>databasir.document_full_text.database_type</code>.
     */
    public void setDatabaseType(String databaseType) {
        this.databaseType = databaseType;
    }

    /**
     * Getter for <code>databasir.document_full_text.table_name</code>.
     */
    public String getTableName() {
        return this.tableName;
    }

    /**
     * Setter for <code>databasir.document_full_text.table_name</code>.
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * Getter for <code>databasir.document_full_text.table_comment</code>.
     */
    public String getTableComment() {
        return this.tableComment;
    }

    /**
     * Setter for <code>databasir.document_full_text.table_comment</code>.
     */
    public void setTableComment(String tableComment) {
        this.tableComment = tableComment;
    }

    /**
     * Getter for <code>databasir.document_full_text.table_description</code>.
     */
    public String getTableDescription() {
        return this.tableDescription;
    }

    /**
     * Setter for <code>databasir.document_full_text.table_description</code>.
     */
    public void setTableDescription(String tableDescription) {
        this.tableDescription = tableDescription;
    }

    /**
     * Getter for <code>databasir.document_full_text.col_name</code>.
     */
    public String getColName() {
        return this.colName;
    }

    /**
     * Setter for <code>databasir.document_full_text.col_name</code>.
     */
    public void setColName(String colName) {
        this.colName = colName;
    }

    /**
     * Getter for <code>databasir.document_full_text.col_comment</code>.
     */
    public String getColComment() {
        return this.colComment;
    }

    /**
     * Setter for <code>databasir.document_full_text.col_comment</code>.
     */
    public void setColComment(String colComment) {
        this.colComment = colComment;
    }

    /**
     * Getter for <code>databasir.document_full_text.col_description</code>.
     */
    public String getColDescription() {
        return this.colDescription;
    }

    /**
     * Setter for <code>databasir.document_full_text.col_description</code>.
     */
    public void setColDescription(String colDescription) {
        this.colDescription = colDescription;
    }

    /**
     * Getter for <code>databasir.document_full_text.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>databasir.document_full_text.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>databasir.document_full_text.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.document_full_text.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DocumentFullText (");

        sb.append(id);
        sb.append(", ").append(groupId);
        sb.append(", ").append(projectId);
        sb.append(", ").append(databaseDocumentId);
        sb.append(", ").append(databaseDocumentVersion);
        sb.append(", ").append(tableDocumentId);
        sb.append(", ").append(tableColumnDocumentId);
        sb.append(", ").append(groupName);
        sb.append(", ").append(groupDescription);
        sb.append(", ").append(projectName);
        sb.append(", ").append(projectDescription);
        sb.append(", ").append(databaseName);
        sb.append(", ").append(schemaName);
        sb.append(", ").append(databaseProductName);
        sb.append(", ").append(databaseType);
        sb.append(", ").append(tableName);
        sb.append(", ").append(tableComment);
        sb.append(", ").append(tableDescription);
        sb.append(", ").append(colName);
        sb.append(", ").append(colComment);
        sb.append(", ").append(colDescription);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
