/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoginPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       userId;
    private String        accessToken;
    private String        refreshToken;
    private LocalDateTime accessTokenExpireAt;
    private LocalDateTime refreshTokenExpireAt;
    private LocalDateTime updateAt;
    private LocalDateTime createAt;

    public LoginPojo() {}

    public LoginPojo(LoginPojo value) {
        this.id = value.id;
        this.userId = value.userId;
        this.accessToken = value.accessToken;
        this.refreshToken = value.refreshToken;
        this.accessTokenExpireAt = value.accessTokenExpireAt;
        this.refreshTokenExpireAt = value.refreshTokenExpireAt;
        this.updateAt = value.updateAt;
        this.createAt = value.createAt;
    }

    public LoginPojo(
        Integer       id,
        Integer       userId,
        String        accessToken,
        String        refreshToken,
        LocalDateTime accessTokenExpireAt,
        LocalDateTime refreshTokenExpireAt,
        LocalDateTime updateAt,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.userId = userId;
        this.accessToken = accessToken;
        this.refreshToken = refreshToken;
        this.accessTokenExpireAt = accessTokenExpireAt;
        this.refreshTokenExpireAt = refreshTokenExpireAt;
        this.updateAt = updateAt;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.login.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.login.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.login.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>databasir.login.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>databasir.login.access_token</code>.
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Setter for <code>databasir.login.access_token</code>.
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * Getter for <code>databasir.login.refresh_token</code>.
     */
    public String getRefreshToken() {
        return this.refreshToken;
    }

    /**
     * Setter for <code>databasir.login.refresh_token</code>.
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    /**
     * Getter for <code>databasir.login.access_token_expire_at</code>.
     */
    public LocalDateTime getAccessTokenExpireAt() {
        return this.accessTokenExpireAt;
    }

    /**
     * Setter for <code>databasir.login.access_token_expire_at</code>.
     */
    public void setAccessTokenExpireAt(LocalDateTime accessTokenExpireAt) {
        this.accessTokenExpireAt = accessTokenExpireAt;
    }

    /**
     * Getter for <code>databasir.login.refresh_token_expire_at</code>.
     */
    public LocalDateTime getRefreshTokenExpireAt() {
        return this.refreshTokenExpireAt;
    }

    /**
     * Setter for <code>databasir.login.refresh_token_expire_at</code>.
     */
    public void setRefreshTokenExpireAt(LocalDateTime refreshTokenExpireAt) {
        this.refreshTokenExpireAt = refreshTokenExpireAt;
    }

    /**
     * Getter for <code>databasir.login.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>databasir.login.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>databasir.login.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.login.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LoginPojo (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(refreshToken);
        sb.append(", ").append(accessTokenExpireAt);
        sb.append(", ").append(refreshTokenExpireAt);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
