/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableTriggerDocumentPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       tableDocumentId;
    private Integer       databaseDocumentId;
    private String        timing;
    private String        manipulation;
    private String        statement;
    private String        triggerCreateAt;
    private LocalDateTime createAt;

    public TableTriggerDocumentPojo() {}

    public TableTriggerDocumentPojo(TableTriggerDocumentPojo value) {
        this.id = value.id;
        this.tableDocumentId = value.tableDocumentId;
        this.databaseDocumentId = value.databaseDocumentId;
        this.timing = value.timing;
        this.manipulation = value.manipulation;
        this.statement = value.statement;
        this.triggerCreateAt = value.triggerCreateAt;
        this.createAt = value.createAt;
    }

    public TableTriggerDocumentPojo(
        Integer       id,
        Integer       tableDocumentId,
        Integer       databaseDocumentId,
        String        timing,
        String        manipulation,
        String        statement,
        String        triggerCreateAt,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.tableDocumentId = tableDocumentId;
        this.databaseDocumentId = databaseDocumentId;
        this.timing = timing;
        this.manipulation = manipulation;
        this.statement = statement;
        this.triggerCreateAt = triggerCreateAt;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.table_trigger_document.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.table_trigger_document.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>databasir.table_trigger_document.table_document_id</code>.
     */
    public Integer getTableDocumentId() {
        return this.tableDocumentId;
    }

    /**
     * Setter for
     * <code>databasir.table_trigger_document.table_document_id</code>.
     */
    public void setTableDocumentId(Integer tableDocumentId) {
        this.tableDocumentId = tableDocumentId;
    }

    /**
     * Getter for
     * <code>databasir.table_trigger_document.database_document_id</code>.
     */
    public Integer getDatabaseDocumentId() {
        return this.databaseDocumentId;
    }

    /**
     * Setter for
     * <code>databasir.table_trigger_document.database_document_id</code>.
     */
    public void setDatabaseDocumentId(Integer databaseDocumentId) {
        this.databaseDocumentId = databaseDocumentId;
    }

    /**
     * Getter for <code>databasir.table_trigger_document.timing</code>.
     */
    public String getTiming() {
        return this.timing;
    }

    /**
     * Setter for <code>databasir.table_trigger_document.timing</code>.
     */
    public void setTiming(String timing) {
        this.timing = timing;
    }

    /**
     * Getter for <code>databasir.table_trigger_document.manipulation</code>.
     */
    public String getManipulation() {
        return this.manipulation;
    }

    /**
     * Setter for <code>databasir.table_trigger_document.manipulation</code>.
     */
    public void setManipulation(String manipulation) {
        this.manipulation = manipulation;
    }

    /**
     * Getter for <code>databasir.table_trigger_document.statement</code>.
     */
    public String getStatement() {
        return this.statement;
    }

    /**
     * Setter for <code>databasir.table_trigger_document.statement</code>.
     */
    public void setStatement(String statement) {
        this.statement = statement;
    }

    /**
     * Getter for
     * <code>databasir.table_trigger_document.trigger_create_at</code>.
     */
    public String getTriggerCreateAt() {
        return this.triggerCreateAt;
    }

    /**
     * Setter for
     * <code>databasir.table_trigger_document.trigger_create_at</code>.
     */
    public void setTriggerCreateAt(String triggerCreateAt) {
        this.triggerCreateAt = triggerCreateAt;
    }

    /**
     * Getter for <code>databasir.table_trigger_document.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.table_trigger_document.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TableTriggerDocumentPojo (");

        sb.append(id);
        sb.append(", ").append(tableDocumentId);
        sb.append(", ").append(databaseDocumentId);
        sb.append(", ").append(timing);
        sb.append(", ").append(manipulation);
        sb.append(", ").append(statement);
        sb.append(", ").append(triggerCreateAt);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
