/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFavoriteProjectPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       userId;
    private Integer       projectId;
    private LocalDateTime createAt;

    public UserFavoriteProjectPojo() {}

    public UserFavoriteProjectPojo(UserFavoriteProjectPojo value) {
        this.id = value.id;
        this.userId = value.userId;
        this.projectId = value.projectId;
        this.createAt = value.createAt;
    }

    public UserFavoriteProjectPojo(
        Integer       id,
        Integer       userId,
        Integer       projectId,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.userId = userId;
        this.projectId = projectId;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.user_favorite_project.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.user_favorite_project.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.user_favorite_project.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>databasir.user_favorite_project.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>databasir.user_favorite_project.project_id</code>.
     */
    public Integer getProjectId() {
        return this.projectId;
    }

    /**
     * Setter for <code>databasir.user_favorite_project.project_id</code>.
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * Getter for <code>databasir.user_favorite_project.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.user_favorite_project.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserFavoriteProjectPojo (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(projectId);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
