/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        email;
    private String        username;
    private String        password;
    private String        nickname;
    private String        avatar;
    private Boolean       enabled;
    private LocalDateTime updateAt;
    private LocalDateTime createAt;

    public UserPojo() {}

    public UserPojo(UserPojo value) {
        this.id = value.id;
        this.email = value.email;
        this.username = value.username;
        this.password = value.password;
        this.nickname = value.nickname;
        this.avatar = value.avatar;
        this.enabled = value.enabled;
        this.updateAt = value.updateAt;
        this.createAt = value.createAt;
    }

    public UserPojo(
        Integer       id,
        String        email,
        String        username,
        String        password,
        String        nickname,
        String        avatar,
        Boolean       enabled,
        LocalDateTime updateAt,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.email = email;
        this.username = username;
        this.password = password;
        this.nickname = nickname;
        this.avatar = avatar;
        this.enabled = enabled;
        this.updateAt = updateAt;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>databasir.user.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>databasir.user.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>databasir.user.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>databasir.user.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>databasir.user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>databasir.user.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>databasir.user.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>databasir.user.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>databasir.user.nickname</code>.
     */
    public String getNickname() {
        return this.nickname;
    }

    /**
     * Setter for <code>databasir.user.nickname</code>.
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * Getter for <code>databasir.user.avatar</code>.
     */
    public String getAvatar() {
        return this.avatar;
    }

    /**
     * Setter for <code>databasir.user.avatar</code>.
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * Getter for <code>databasir.user.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>databasir.user.enabled</code>.
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Getter for <code>databasir.user.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>databasir.user.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>databasir.user.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>databasir.user.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPojo (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(nickname);
        sb.append(", ").append(avatar);
        sb.append(", ").append(enabled);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
