/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.records;


import com.databasir.dao.tables.DocumentDescription;
import com.databasir.dao.tables.pojos.DocumentDescriptionPojo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * custom document description
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentDescriptionRecord extends UpdatableRecordImpl<DocumentDescriptionRecord> implements Record8<Integer, String, Integer, String, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>databasir.document_description.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>databasir.document_description.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>databasir.document_description.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>databasir.document_description.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>databasir.document_description.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>databasir.document_description.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>databasir.document_description.table_name</code>.
     */
    public void setTableName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>databasir.document_description.table_name</code>.
     */
    public String getTableName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>databasir.document_description.column_name</code>.
     */
    public void setColumnName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>databasir.document_description.column_name</code>.
     */
    public String getColumnName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>databasir.document_description.update_by</code>.
     */
    public void setUpdateBy(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>databasir.document_description.update_by</code>.
     */
    public Integer getUpdateBy() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>databasir.document_description.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>databasir.document_description.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>databasir.document_description.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>databasir.document_description.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, Integer, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, Integer, String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DocumentDescription.DOCUMENT_DESCRIPTION.ID;
    }

    @Override
    public Field<String> field2() {
        return DocumentDescription.DOCUMENT_DESCRIPTION.CONTENT;
    }

    @Override
    public Field<Integer> field3() {
        return DocumentDescription.DOCUMENT_DESCRIPTION.PROJECT_ID;
    }

    @Override
    public Field<String> field4() {
        return DocumentDescription.DOCUMENT_DESCRIPTION.TABLE_NAME;
    }

    @Override
    public Field<String> field5() {
        return DocumentDescription.DOCUMENT_DESCRIPTION.COLUMN_NAME;
    }

    @Override
    public Field<Integer> field6() {
        return DocumentDescription.DOCUMENT_DESCRIPTION.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return DocumentDescription.DOCUMENT_DESCRIPTION.UPDATE_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return DocumentDescription.DOCUMENT_DESCRIPTION.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public Integer component3() {
        return getProjectId();
    }

    @Override
    public String component4() {
        return getTableName();
    }

    @Override
    public String component5() {
        return getColumnName();
    }

    @Override
    public Integer component6() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdateAt();
    }

    @Override
    public LocalDateTime component8() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public Integer value3() {
        return getProjectId();
    }

    @Override
    public String value4() {
        return getTableName();
    }

    @Override
    public String value5() {
        return getColumnName();
    }

    @Override
    public Integer value6() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdateAt();
    }

    @Override
    public LocalDateTime value8() {
        return getCreateAt();
    }

    @Override
    public DocumentDescriptionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DocumentDescriptionRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public DocumentDescriptionRecord value3(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public DocumentDescriptionRecord value4(String value) {
        setTableName(value);
        return this;
    }

    @Override
    public DocumentDescriptionRecord value5(String value) {
        setColumnName(value);
        return this;
    }

    @Override
    public DocumentDescriptionRecord value6(Integer value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public DocumentDescriptionRecord value7(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    public DocumentDescriptionRecord value8(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public DocumentDescriptionRecord values(Integer value1, String value2, Integer value3, String value4, String value5, Integer value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocumentDescriptionRecord
     */
    public DocumentDescriptionRecord() {
        super(DocumentDescription.DOCUMENT_DESCRIPTION);
    }

    /**
     * Create a detached, initialised DocumentDescriptionRecord
     */
    public DocumentDescriptionRecord(Integer id, String content, Integer projectId, String tableName, String columnName, Integer updateBy, LocalDateTime updateAt, LocalDateTime createAt) {
        super(DocumentDescription.DOCUMENT_DESCRIPTION);

        setId(id);
        setContent(content);
        setProjectId(projectId);
        setTableName(tableName);
        setColumnName(columnName);
        setUpdateBy(updateBy);
        setUpdateAt(updateAt);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised DocumentDescriptionRecord
     */
    public DocumentDescriptionRecord(DocumentDescriptionPojo value) {
        super(DocumentDescription.DOCUMENT_DESCRIPTION);

        if (value != null) {
            setId(value.getId());
            setContent(value.getContent());
            setProjectId(value.getProjectId());
            setTableName(value.getTableName());
            setColumnName(value.getColumnName());
            setUpdateBy(value.getUpdateBy());
            setUpdateAt(value.getUpdateAt());
            setCreateAt(value.getCreateAt());
        }
    }
}
