/*
 * This file is generated by jOOQ.
 */
package com.databasir.dao.tables.records;


import com.databasir.dao.tables.DocumentFullText;
import com.databasir.dao.tables.pojos.DocumentFullTextPojo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DocumentFullTextRecord extends UpdatableRecordImpl<DocumentFullTextRecord> implements Record21<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>databasir.document_full_text.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>databasir.document_full_text.group_id</code>. ref to
     * group.id
     */
    public void setGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.group_id</code>. ref to
     * group.id
     */
    public Integer getGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>databasir.document_full_text.project_id</code>. ref to
     * project.id, may null
     */
    public void setProjectId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.project_id</code>. ref to
     * project.id, may null
     */
    public Integer getProjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>databasir.document_full_text.database_document_id</code>. ref to
     * database_document.id, may null
     */
    public void setDatabaseDocumentId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>databasir.document_full_text.database_document_id</code>. ref to
     * database_document.id, may null
     */
    public Integer getDatabaseDocumentId() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>databasir.document_full_text.database_document_version</code>. rf
     * to database_document.version, may null
     */
    public void setDatabaseDocumentVersion(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>databasir.document_full_text.database_document_version</code>. rf
     * to database_document.version, may null
     */
    public Integer getDatabaseDocumentVersion() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>databasir.document_full_text.table_document_id</code>.
     * ref to table_document.id, may null
     */
    public void setTableDocumentId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.table_document_id</code>.
     * ref to table_document.id, may null
     */
    public Integer getTableDocumentId() {
        return (Integer) get(5);
    }

    /**
     * Setter for
     * <code>databasir.document_full_text.table_column_document_id</code>. ref
     * to table_column_document.id, may null
     */
    public void setTableColumnDocumentId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>databasir.document_full_text.table_column_document_id</code>. ref
     * to table_column_document.id, may null
     */
    public Integer getTableColumnDocumentId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>databasir.document_full_text.group_name</code>.
     */
    public void setGroupName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.group_name</code>.
     */
    public String getGroupName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>databasir.document_full_text.group_description</code>.
     */
    public void setGroupDescription(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.group_description</code>.
     */
    public String getGroupDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>databasir.document_full_text.project_name</code>.
     */
    public void setProjectName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.project_name</code>.
     */
    public String getProjectName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>databasir.document_full_text.project_description</code>.
     */
    public void setProjectDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.project_description</code>.
     */
    public String getProjectDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>databasir.document_full_text.database_name</code>.
     */
    public void setDatabaseName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.database_name</code>.
     */
    public String getDatabaseName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>databasir.document_full_text.schema_name</code>.
     */
    public void setSchemaName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.schema_name</code>.
     */
    public String getSchemaName() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>databasir.document_full_text.database_product_name</code>.
     */
    public void setDatabaseProductName(String value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>databasir.document_full_text.database_product_name</code>.
     */
    public String getDatabaseProductName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>databasir.document_full_text.database_type</code>.
     */
    public void setDatabaseType(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.database_type</code>.
     */
    public String getDatabaseType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>databasir.document_full_text.table_name</code>.
     */
    public void setTableName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.table_name</code>.
     */
    public String getTableName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>databasir.document_full_text.table_comment</code>.
     */
    public void setTableComment(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.table_comment</code>.
     */
    public String getTableComment() {
        return (String) get(16);
    }

    /**
     * Setter for <code>databasir.document_full_text.col_name</code>.
     */
    public void setColName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.col_name</code>.
     */
    public String getColName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>databasir.document_full_text.col_comment</code>.
     */
    public void setColComment(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.col_comment</code>.
     */
    public String getColComment() {
        return (String) get(18);
    }

    /**
     * Setter for <code>databasir.document_full_text.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>databasir.document_full_text.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>databasir.document_full_text.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.GROUP_ID;
    }

    @Override
    public Field<Integer> field3() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.PROJECT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.DATABASE_DOCUMENT_ID;
    }

    @Override
    public Field<Integer> field5() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.DATABASE_DOCUMENT_VERSION;
    }

    @Override
    public Field<Integer> field6() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.TABLE_DOCUMENT_ID;
    }

    @Override
    public Field<Integer> field7() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.TABLE_COLUMN_DOCUMENT_ID;
    }

    @Override
    public Field<String> field8() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.GROUP_NAME;
    }

    @Override
    public Field<String> field9() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.GROUP_DESCRIPTION;
    }

    @Override
    public Field<String> field10() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.PROJECT_NAME;
    }

    @Override
    public Field<String> field11() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.PROJECT_DESCRIPTION;
    }

    @Override
    public Field<String> field12() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.DATABASE_NAME;
    }

    @Override
    public Field<String> field13() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.SCHEMA_NAME;
    }

    @Override
    public Field<String> field14() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.DATABASE_PRODUCT_NAME;
    }

    @Override
    public Field<String> field15() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.DATABASE_TYPE;
    }

    @Override
    public Field<String> field16() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.TABLE_NAME;
    }

    @Override
    public Field<String> field17() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.TABLE_COMMENT;
    }

    @Override
    public Field<String> field18() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.COL_NAME;
    }

    @Override
    public Field<String> field19() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.COL_COMMENT;
    }

    @Override
    public Field<LocalDateTime> field20() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.UPDATE_AT;
    }

    @Override
    public Field<LocalDateTime> field21() {
        return DocumentFullText.DOCUMENT_FULL_TEXT.CREATE_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGroupId();
    }

    @Override
    public Integer component3() {
        return getProjectId();
    }

    @Override
    public Integer component4() {
        return getDatabaseDocumentId();
    }

    @Override
    public Integer component5() {
        return getDatabaseDocumentVersion();
    }

    @Override
    public Integer component6() {
        return getTableDocumentId();
    }

    @Override
    public Integer component7() {
        return getTableColumnDocumentId();
    }

    @Override
    public String component8() {
        return getGroupName();
    }

    @Override
    public String component9() {
        return getGroupDescription();
    }

    @Override
    public String component10() {
        return getProjectName();
    }

    @Override
    public String component11() {
        return getProjectDescription();
    }

    @Override
    public String component12() {
        return getDatabaseName();
    }

    @Override
    public String component13() {
        return getSchemaName();
    }

    @Override
    public String component14() {
        return getDatabaseProductName();
    }

    @Override
    public String component15() {
        return getDatabaseType();
    }

    @Override
    public String component16() {
        return getTableName();
    }

    @Override
    public String component17() {
        return getTableComment();
    }

    @Override
    public String component18() {
        return getColName();
    }

    @Override
    public String component19() {
        return getColComment();
    }

    @Override
    public LocalDateTime component20() {
        return getUpdateAt();
    }

    @Override
    public LocalDateTime component21() {
        return getCreateAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGroupId();
    }

    @Override
    public Integer value3() {
        return getProjectId();
    }

    @Override
    public Integer value4() {
        return getDatabaseDocumentId();
    }

    @Override
    public Integer value5() {
        return getDatabaseDocumentVersion();
    }

    @Override
    public Integer value6() {
        return getTableDocumentId();
    }

    @Override
    public Integer value7() {
        return getTableColumnDocumentId();
    }

    @Override
    public String value8() {
        return getGroupName();
    }

    @Override
    public String value9() {
        return getGroupDescription();
    }

    @Override
    public String value10() {
        return getProjectName();
    }

    @Override
    public String value11() {
        return getProjectDescription();
    }

    @Override
    public String value12() {
        return getDatabaseName();
    }

    @Override
    public String value13() {
        return getSchemaName();
    }

    @Override
    public String value14() {
        return getDatabaseProductName();
    }

    @Override
    public String value15() {
        return getDatabaseType();
    }

    @Override
    public String value16() {
        return getTableName();
    }

    @Override
    public String value17() {
        return getTableComment();
    }

    @Override
    public String value18() {
        return getColName();
    }

    @Override
    public String value19() {
        return getColComment();
    }

    @Override
    public LocalDateTime value20() {
        return getUpdateAt();
    }

    @Override
    public LocalDateTime value21() {
        return getCreateAt();
    }

    @Override
    public DocumentFullTextRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value2(Integer value) {
        setGroupId(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value3(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value4(Integer value) {
        setDatabaseDocumentId(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value5(Integer value) {
        setDatabaseDocumentVersion(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value6(Integer value) {
        setTableDocumentId(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value7(Integer value) {
        setTableColumnDocumentId(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value8(String value) {
        setGroupName(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value9(String value) {
        setGroupDescription(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value10(String value) {
        setProjectName(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value11(String value) {
        setProjectDescription(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value12(String value) {
        setDatabaseName(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value13(String value) {
        setSchemaName(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value14(String value) {
        setDatabaseProductName(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value15(String value) {
        setDatabaseType(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value16(String value) {
        setTableName(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value17(String value) {
        setTableComment(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value18(String value) {
        setColName(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value19(String value) {
        setColComment(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value20(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord value21(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public DocumentFullTextRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, LocalDateTime value20, LocalDateTime value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocumentFullTextRecord
     */
    public DocumentFullTextRecord() {
        super(DocumentFullText.DOCUMENT_FULL_TEXT);
    }

    /**
     * Create a detached, initialised DocumentFullTextRecord
     */
    public DocumentFullTextRecord(Integer id, Integer groupId, Integer projectId, Integer databaseDocumentId, Integer databaseDocumentVersion, Integer tableDocumentId, Integer tableColumnDocumentId, String groupName, String groupDescription, String projectName, String projectDescription, String databaseName, String schemaName, String databaseProductName, String databaseType, String tableName, String tableComment, String colName, String colComment, LocalDateTime updateAt, LocalDateTime createAt) {
        super(DocumentFullText.DOCUMENT_FULL_TEXT);

        setId(id);
        setGroupId(groupId);
        setProjectId(projectId);
        setDatabaseDocumentId(databaseDocumentId);
        setDatabaseDocumentVersion(databaseDocumentVersion);
        setTableDocumentId(tableDocumentId);
        setTableColumnDocumentId(tableColumnDocumentId);
        setGroupName(groupName);
        setGroupDescription(groupDescription);
        setProjectName(projectName);
        setProjectDescription(projectDescription);
        setDatabaseName(databaseName);
        setSchemaName(schemaName);
        setDatabaseProductName(databaseProductName);
        setDatabaseType(databaseType);
        setTableName(tableName);
        setTableComment(tableComment);
        setColName(colName);
        setColComment(colComment);
        setUpdateAt(updateAt);
        setCreateAt(createAt);
    }

    /**
     * Create a detached, initialised DocumentFullTextRecord
     */
    public DocumentFullTextRecord(DocumentFullTextPojo value) {
        super(DocumentFullText.DOCUMENT_FULL_TEXT);

        if (value != null) {
            setId(value.getId());
            setGroupId(value.getGroupId());
            setProjectId(value.getProjectId());
            setDatabaseDocumentId(value.getDatabaseDocumentId());
            setDatabaseDocumentVersion(value.getDatabaseDocumentVersion());
            setTableDocumentId(value.getTableDocumentId());
            setTableColumnDocumentId(value.getTableColumnDocumentId());
            setGroupName(value.getGroupName());
            setGroupDescription(value.getGroupDescription());
            setProjectName(value.getProjectName());
            setProjectDescription(value.getProjectDescription());
            setDatabaseName(value.getDatabaseName());
            setSchemaName(value.getSchemaName());
            setDatabaseProductName(value.getDatabaseProductName());
            setDatabaseType(value.getDatabaseType());
            setTableName(value.getTableName());
            setTableComment(value.getTableComment());
            setColName(value.getColName());
            setColComment(value.getColComment());
            setUpdateAt(value.getUpdateAt());
            setCreateAt(value.getCreateAt());
        }
    }
}
